### ISSUE TITLE
python common error

### ISSUE THREAD

**Issue by datayears** [datayears/recommendSystemSimple#3]
1
/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py:3457: FutureWarning: Passing in 'datetime64' dtype with no frequency is deprecated and will raise in a future version. Please pass in 'datetime64[ns]' instead.
  return self.apply('astype', dtype=dtype, **kwargs)
Error: ufunc subtract cannot use operands with types dtype('S10') and dtype('<M8[ns]')

**Comment by datayears** [comment]
36000000 rows completed
36200000 rows completed
Error: ufunc subtract cannot use operands with types dtype('S10') and dtype('<M8[ns]')
Error: ufunc subtract cannot use operands with types dtype('S10') and dtype('<M8[ns]')
36400000 rows completed
36600000 rows completed
36800000 rows completed
37000000 rows completed
10000 rows completed
20000 rows completed
30000 rows completed

**Comment by datayears** [comment]
37000000 rows completed
10000 rows completed
20000 rows completed
30000 rows completed
40000 rows completed
50000 rows completed
60000 rows completed
70000 rows completed
Traceback (most recent call last):
  File "1_random_forest.py", line 111, in <module>
    pre_process(chunk)
  File "1_random_forest.py", line 27, in pre_process
    data['srch_duration'] = data['srch_duration'].apply(lambda td: td/np.timedelta64(1, 'D'))
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 2510, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1521, in pandas._libs.lib.map_infer
  File "1_random_forest.py", line 27, in <lambda>
    data['srch_duration'] = data['srch_duration'].apply(lambda td: td/np.timedelta64(1, 'D'))
TypeError: ufunc divide cannot use operands with types dtype('int64') and dtype('<m8[D]')
